export const GEOLOCATION_REQUEST = 'GEOLOCATION_REQUEST';
export const GEOLOCATION_SUCCESS = 'GEOLOCATION_SUCCESS';
export const GEOLOCATION_FAIL = 'GEOLOCATION_FAIL';

export const GEOCODER_REQUEST = 'GEOCODER_REQUEST';
export const GEOCODER_SUCCESS = 'GEOCODER_SUCCESS';
export const GEOCODER_FAIL = 'GEOCODER_FAIL';
