export const JOB_LIST_REQUEST = 'JOB_LIST_REQUEST';
export const JOB_LIST_SUCCESS = 'JOB_LIST_SUCCESS';
export const JOB_LIST_FAIL = 'JOB_LIST_FAIL';

export const JOB_NEXT_PAGE_REQUEST = 'JOB_NEXT_PAGE_REQUEST';
export const JOB_NEXT_PAGE_SUCCESS = 'JOB_NEXT_PAGE_SUCCESS';
export const JOB_NEXT_PAGE_FAIL = 'JOB_NEXT_PAGE_FAIL';

export const JOB_DETAILS_REQUEST = 'JOB_DETAILS_REQUEST';
export const JOB_DETAILS_SUCCESS = 'JOB_DETAILS_SUCCESS';
export const JOB_DETAILS_FAIL = 'JOB_DETAILS_FAIL';
export const JOB_DETAILS_RESET = 'JOB_DETAILS_RESET';
